name: Deploy to DigitalOcean

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            set -e

            cd /home/deploy/apps/miapp

            echo "== Sync repo =="
            git fetch --all
            git reset --hard origin/main

            echo "== Install deps =="
            npm ci

            echo "== Build frontend =="
            npm run build

            echo "== Publish frontend =="
            rm -rf /var/www/miapp/*
            cp -r dist/* /var/www/miapp/

            echo "== Restart backend =="
            pm2 restart miapp-api || pm2 start "npm run server" --name miapp-api
            pm2 save

            echo "== Reload nginx =="
            sudo nginx -t
            sudo systemctl reload nginx

            echo "✅ Deploy finished"
